version: '3.1'

services:

  btcd:
    image: btcd
    container_name: btcd
    build:
      context: btcd/
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    volumes:
      - shared:/rpc
    networks:
      nodes:
        ipv4_address: 10.5.0.5
    entrypoint: ["./start-btcd.sh"]
  alice:
    container_name: "alice"
    domainname: alice.client
    hostname: alice
    build:
      context: ../
      dockerfile: docker/alice/Dockerfile
    volumes:
      - ./alice_node:/root/.lnd
    ports:
      - 9735:9735
      - 10009:10009
    links:
      - "btcd:blockchain"
    networks:
      nodes:
        ipv4_address: 10.5.0.2
  breez:
    container_name: "breez"
    domainname: breez_node.server
    hostname: "breez_node"
    build:
      context: ../
      dockerfile: docker/breez/Dockerfile
    volumes:
      - shared:/rpc
      - ./breez_node:/root/.lnd
    ports:
      - 9736:9735
      - 10010:10009
    links:
      - "btcd:blockchain"
    networks:
      nodes:
        ipv4_address: 10.5.0.3
  breez_server:
    container_name: "breez_server"
    build:
      context: ../
      dockerfile: docker/breez_server/Dockerfile
    depends_on:
      - breez
    volumes:
      - ./breez_node:/root/breez_node
    links:
      - "postgres:postgres"
      - "redis:redis"
    networks:
      nodes:
        ipv4_address: 10.5.0.4
  lspd:
    container_name: "lspd"
    build:
      context: ../
      dockerfile: docker/lspd/Dockerfile
    depends_on:
      - breez_server
    volumes:
      - ./breez_node:/root/breez_node
    links:
      - "postgres_interceptor:postgres_interceptor"
    networks:
      nodes:
        ipv4_address: 10.5.0.9
  postgres:
    image: postgres
    networks:
      nodes:
        ipv4_address: 10.5.0.6
    environment:
      POSTGRES_PASSWORD: test
  postgres_interceptor:
    image: postgres
    networks:
      nodes:
        ipv4_address: 10.5.0.8
    environment:
      POSTGRES_PASSWORD: test
  redis:
    networks:
      nodes:
        ipv4_address: 10.5.0.7
    image: redis:5.0
volumes:
  shared:
    driver: local
networks:
  nodes:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16