version: '3.1'

services:

  btcd:
    image: btcd
    container_name: btcd
    build:
      context: btcd/
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    volumes:
      - shared:/rpc
    ports:
      - 18556:18556
    networks:
      nodes:
        ipv4_address: 10.5.0.5
    entrypoint: ["./start-btcd.sh"]
  alice:
    container_name: "alice"
    domainname: alice.client
    hostname: alice
    build:
      context: ../
      dockerfile: docker/alice/Dockerfile
    volumes:
      - ${TEST_DIR}/alice_node:/root/.lnd
    ports:
      - 9735:9735
      - 10009:10009
      - 50053:50053
    links:
      - "btcd:blockchain"
    depends_on:
      - "btcd"
    networks:
      nodes:
        ipv4_address: 10.5.0.2
  bob:
    container_name: "bob"
    domainname: bob.client
    hostname: bob
    build:
      context: ../
      dockerfile: docker/alice/Dockerfile
    volumes:
      - ${TEST_DIR}/bob_node:/root/.lnd
    ports:
      - 9737:9735
      - 10011:10009
      - 50054:50053
    depends_on:
      - "btcd"
    links:
      - "btcd:blockchain"
    networks:
      nodes:
        ipv4_address: 10.5.0.10
  lnd:
    container_name: "lnd"
    domainname: lnd.client
    hostname: "lnd_node"
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    volumes:
      - shared:/rpc
      - ${TEST_DIR}/lnd:/root/.lnd
    ports:
      - 9739:9735
      - 10013:10009
    links:
      - "btcd:blockchain"
    depends_on:
      - "btcd"
    networks:
      nodes:
        ipv4_address: 10.5.0.12
  breez:
    container_name: "breez"
    domainname: breez_node.server
    hostname: "breez_node"
    build:
      context: ../
      dockerfile: docker/breez/Dockerfile
    volumes:
      - shared:/rpc
      - ${TEST_DIR}/breez_node:/root/.lnd
    ports:
      - 9736:9735
      - 10010:10009
    links:
      - "btcd:blockchain"
    depends_on:
      - "btcd"
    networks:
      nodes:
        ipv4_address: 10.5.0.3
  subswap_node:
    container_name: "subswap_node"
    domainname: subswap_node.server
    hostname: "subswap_node"
    build:
      context: ../
      dockerfile: docker/breez/Dockerfile
    volumes:
      - shared:/rpc
      - ${TEST_DIR}/subswap_node:/root/.lnd
    ports:
      - 9738:9735
      - 10012:10009
    links:
      - "btcd:blockchain"
    depends_on:
      - "btcd"
    networks:
      nodes:
        ipv4_address: 10.5.0.11
  breez_server:
    container_name: "breez_server"
    build:
      context: ../
      dockerfile: docker/breez_server/Dockerfile
    depends_on:
      - breez
      - subswap_node
      - lspd
      - postgres
    volumes:
      - ${TEST_DIR}/breez_node:/root/breez_node
      - ${TEST_DIR}/subswap_node:/root/subswap_node
    links:
      - "postgres:postgres"
      - "redis:redis"
    networks:
      nodes:
        ipv4_address: 10.5.0.4
  lspd:
    container_name: "lspd"
    build:
      context: ../
      dockerfile: docker/lspd/Dockerfile
    volumes:
      - ${TEST_DIR}/breez_node:/root/breez_node
    links:
      - "postgres_interceptor:postgres_interceptor"
    depends_on:
      - postgres_interceptor
      - breez
    networks:
      nodes:
        ipv4_address: 10.5.0.9
  postgres:
    image: postgres
    networks:
      nodes:
        ipv4_address: 10.5.0.6
    environment:
      POSTGRES_PASSWORD: test
  postgres_interceptor:
    image: postgres
    networks:
      nodes:
        ipv4_address: 10.5.0.8
    environment:
      POSTGRES_PASSWORD: test
  redis:
    networks:
      nodes:
        ipv4_address: 10.5.0.7
    build:
      context: ./redis
volumes:
  shared:
    driver: local
networks:
  nodes:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16